FROM berkeleyskypilot/skypilot-k8s:latest

COPY --chown=sky . /skypilot/sky/

# Set PYTHONUNBUFFERED=1 to have Python print to stdout/stderr immediately
ENV PYTHONUNBUFFERED=1

# Install SkyPilot
RUN cd /skypilot/sky && pip install -e .[kubernetes] && pip install uvicorn fastapi httpx
